### ISSUE TITLE
Dockerfile not working out the box with VIS tutorial code

### ISSUE THREAD

**Issue by javadan** [danforthcenter/plantcv#255]
Hi,

I'm trying out the Dockerfile.  I copied every line of code from the VIS tutorial and put it in a python script, and mapped a folder to the container, with a png and the script..

It first crashed on this line, because it needed two arguments:
   ab_cnt = pcv.logical_or(maskeda_thresh1)

That field isn't used later though, so I removed it.  (So probably remove that line from the tutorial.)

It then crashes on this line, but I'm not sure how to get past this one.

```
  File "/data/test-script.py", line 85, in main
    obj, mask = pcv.object_composition(img, roi_objects, hierarchy3)
  File "/opt/conda/lib/python2.7/site-packages/plantcv-0+unknown-py2.7.egg/plantcv/plantcv/object_composition.py", line 37, in object_composition
    r, g, b = cv2.split(ori_img)
ValueError: too many values to unpack

```

I'm guessing the issue is that it's just an ancient python and opencv, and the problem doesn't exist any more.  

In which case, maybe this issue should be to update the Dockerfile.  Is there an updated one somewhere?  

Thanks
Dan

**Comment by nfahlgren** [comment]
Hi @javadan,

You are correct, there is a missing argument in `ab_cnt = pcv.logical_or(maskeda_thresh1)` in the tutorial, but since it is not used we can remove that line.

I had forgotten until you mentioned it that the Docker containers are built with Python2 and OpenCV2. While this should work, I do need to update it to use Python3 and OpenCV3 instead. However, I suspect the issue you are having is that your images are RGBA (with the alpha channel) rather than RGB, so the split receives 4 return values instead of the expected 4. If this is the case, then with the VIS tutorial setup:

```python
img, path, filename = pcv.readimage(args.image)
np.shape(img)
```

will return 4 as the third dimension. The workaround for now is to explicitly read the image in as RGB (rather than in it's native format):

```python
img, path, filename = pcv.readimage(args.image, mode="rgb")
```

If that is not the case, please let us know.

Thanks!

**Comment by javadan** [comment]
Hi Noah, 

Sorry for the delay, am only working on this stuff one day/week.
Makes sense about the alpha.  I added the mode="rgb", and it got me to the next issue.

```
  File "/data/test.py", line 101, in main
    color_header, color_data, color_img = pcv.analyze_color(img, kept_mask, 256, 'all', 'v', 'img', 300, args.outdir + '/' + filename)
TypeError: analyze_color() takes at most 7 arguments (8 given)
```
I looked in the code for the definition: 

`def analyze_color(rgb_img, mask, bins, hist_plot_type=None, pseudo_channel='v', pseudo_bkg='img', filename=False):`

And decided to just remove the '300' as it looks like the odd one out.

That seems to have done something. My 4.png is now accompanied by a bunch of jpgs.
4_all_hist.svg  4_boundary1680.jpg  4_mask.jpg  4_shapes.jpg  4_v_pseudo_on_img.jpg

Seems to be working.  (Now just gotta work out how to view them from my google cloud console)

Thanks
Dan

**Comment by nfahlgren** [comment]
Hi Dan,

Glad it’s working now! You were correct about removing the 300 input, so looks like we need to remove that from the tutorial also.

**Comment by javadan** [comment]
Hi

I need to reopen this issue.  Didn't look at the project for a couple of months, but tried running the same command that worked before, and it's stopped working.

docker run -v /home/daniel/opencv:/data danforthcenter/plantcv python /data/test.py -i /data/plant.png -o /data -r /data/plantcv-results.txt

Traceback (most recent call last):
  File "/data/test.py", line 3, in <module>
    import cv2
  File "/opt/conda/lib/python2.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

**Comment by nfahlgren** [comment]
Hi @javadan, we just merged an update to the Dockerfile that I'm hoping fixes this issue. The new container is built using a container base from Jupyter and uses Python 3 now instead of 2. We updated the documentation to discuss some of the new features/usage: https://plantcv.readthedocs.io/en/latest/installation/#using-plantcv-containers

**Comment by javadan** [comment]
Hi Noah

Thanks,
I'm getting an error still:

```
Traceback (most recent call last):
  File "/work/test.py", line 122, in <module>
    main()
  File "/work/test.py", line 83, in main
    roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img, 'partial', roi1, roi_hierarchy, id_objects, obj_hierarchy)
  File "/opt/conda/lib/python3.7/site-packages/plantcv-3.4.1+17.g7d5ad86-py3.7.egg/plantcv/plantcv/roi_objects.py", line 50, in roi_objects
    if roi_type.upper() == 'PARTIAL' or roi_type.upper() == 'LARGEST':
AttributeError: 'numpy.ndarray' object has no attribute 'upper'
```

Perhaps the VIS pipeline has changed?

Attaching my code from last time it was working:

```

#!/usr/bin/python
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv

### Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-r","--result", help="result file.", required= False )
    parser.add_argument("-w","--writeimg", help="write out images.", default=False)
    parser.add_argument("-D", "--debug", help="can be set to 'print' or 'none' (or 'plot' if in jupyter) prints intermediate images.", default=None)
    args = parser.parse_args()
    return args

### Main pipeline
def main():
    # Get options
    args = options()

    pcv.params.debug=args.debug
    pcv.params.debug_outdir=args.outdir

    # Read image
    img, path, filename = pcv.readimage(args.image, mode="rgb")

    # Pipeline step

        # Convert RGB to HSV and extract the Saturation channel
    s = pcv.rgb2gray_hsv(img, 's') 
    s_thresh = pcv.threshold.binary(s, 85, 255, 'light')

        # Median Filter
    s_mblur = pcv.median_blur(s_thresh, 5)
    s_cnt = pcv.median_blur(s_thresh, 5)

    # Convert RGB to LAB and extract the Blue channel
    b = pcv.rgb2gray_lab(img, 'b')

    # Threshold the blue image
    b_thresh = pcv.threshold.binary(b, 160, 255, 'light')
    b_cnt = pcv.threshold.binary(b, 160, 255, 'light')

    # Fill small objects
    b_fill = pcv.fill(b_thresh, 10)
    # Join the thresholded saturation and blue-yellow images
    bs = pcv.logical_or(s_mblur, b_cnt)
    # Apply Mask (for vis images, mask_color=white)
    masked = pcv.apply_mask(img, bs, 'white')


        # Convert RGB to LAB and extract the Green-Magenta and Blue-Yellow channels
    masked_a = pcv.rgb2gray_lab(masked, 'a')
    masked_b = pcv.rgb2gray_lab(masked, 'b')

    # Threshold the green-magenta and blue images
    maskeda_thresh = pcv.threshold.binary(masked_a, 115, 255, 'dark')
    maskeda_thresh1 = pcv.threshold.binary(masked_a, 135, 255, 'light')
    maskedb_thresh = pcv.threshold.binary(masked_b, 128, 255, 'light')

    # Join the thresholded saturation and blue-yellow images (OR)
    ab1 = pcv.logical_or(maskeda_thresh, maskedb_thresh)
    ab = pcv.logical_or(maskeda_thresh1, ab1)
    #ab_cnt = pcv.logical_or(maskeda_thresh1)

    # Fill small objects
    ab_fill = pcv.fill(ab, 200)

    # Apply mask (for vis images, mask_color=white)
    masked2 = pcv.apply_mask(masked, ab_fill, 'white')

        # Identify objects
    id_objects, obj_hierarchy = pcv.find_objects(masked2, ab_fill)

        # Define ROI
    roi1, roi_hierarchy= pcv.roi.rectangle(x=100, y=100, h=200, w=200, img=masked2)

        # Decide which objects to keep
    roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img, 'partial', roi1, roi_hierarchy, id_objects, obj_hierarchy)
        # Object combine kept objects
    obj, mask = pcv.object_composition(img, roi_objects, hierarchy3)


    ############### Analysis ################

    outfile=False
    if args.writeimg==True:
        outfile=args.outdir+"/"+filename

    # Find shape properties, output shape image (optional)
    shape_header, shape_data, shape_img = pcv.analyze_object(img, obj, mask, args.outdir + '/' + filename)

    # Shape properties relative to user boundary line (optional)
    boundary_header, boundary_data, boundary_img1 = pcv.analyze_bound_horizontal(img, obj, mask, 1680, args.outdir + '/' + filename)

    # Determine color properties: Histograms, Color Slices and Pseudocolored Images, output color analyzed images (optional)
    color_header, color_data, color_img = pcv.analyze_color(img, kept_mask, 256, 'all', 'v', 'img', args.outdir + '/' + filename)

    # Write shape and color data to results file
    result=open(args.result,"a")
    result.write('\t'.join(map(str,shape_header)))
    result.write("\n")
    result.write('\t'.join(map(str,shape_data)))
    result.write("\n")
    for row in shape_img:  
        result.write('\t'.join(map(str,row)))
        result.write("\n")
    result.write('\t'.join(map(str,color_header)))
    result.write("\n")
    result.write('\t'.join(map(str,color_data)))
    result.write("\n")
    for row in color_img:
        result.write('\t'.join(map(str,row)))
        result.write("\n")
    result.close()

if __name__ == '__main__':
    main()

```

**Comment by HaleySchuhl** [comment]
Hi @javadan ,

Since you're using an updated version of PlantCV, one of the things that has changed is that the `pcv.roi_objects()` function now has a default value for `roi_type`, which means we had to reorder the parameters. It's expected the parameters in this order unless parameter names are stated: `roi_objects(img, roi_contour, roi_hierarchy, object_contour, obj_hierarchy, roi_type='partial')`. We suggest stating parameter names to make scripts more robust, but you should also have this error resolved by putting 'partial' as the last parameter. 

```
# Decide which objects to keep
roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img, roi1, roi_hierarchy, id_objects, obj_hierarchy, 'partial')
``` 

Looking at your script, it looks like there are a few other lines of code that will need updating to be compatible with the current version of PlantCV. We record all syntax changes on the [PlantCV Updating Documentation](https://plantcv.readthedocs.io/en/latest/updating/). The functions that collect data no longer return it to the user, but instead data gets stored to the Outputs class. This streamlines the process of printing out data to a file. There is also no longer a `filename` parameter in most functions. After updating these functions that have changed the end of your script should look something like this: 

```
# Find shape properties, output shape image (optional)
    shape_img = pcv.analyze_object(img, obj, mask)

    # Shape properties relative to user boundary line (optional)
    boundary_img1 = pcv.analyze_bound_horizontal(img, obj, mask, 1680)

    # Determine color properties: Histograms, Color Slices and Pseudocolored Images, output color analyzed images (optional)
    color_img = pcv.analyze_color(img, kept_mask, 256, 'all', 'v', 'img')

    # Write shape and color data to results file
    pcv.print_results(filename=args.result)

if __name__ == '__main__':
    main()
```
Let us know if this resolves the error you were getting!

**Comment by javadan** [comment]
Hi Haley

Thanks for the update, yes, managed to get it working again with your advice.

PS. There was one more little issue, where it wouldn't output the images, even if I asked it to with -w, unless I also added the debug parameter, but maybe that's standard.  

Regards
