### ISSUE TITLE
[json2csv] IndexError: list index out of range error message

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#401]
When running json2csv, I get the following error output on the command line:

`Traceback (most recent call last):
  File "C:\path\to\plantcv\plantcv\plantcv-utils.py", line 57, in <module>
    main()
  File "C:\path\to\plantcv\plantcv\plantcv-utils.py", line 52, in main
    options()
  File "C:\path\to\plantcv\plantcv\plantcv-utils.py", line 34, in options
    args.func(args)
  File "C:\path\to\plantcv\plantcv\plantcv-utils.py", line 42, in run_json2csv
    plantcv.utils.json2csv(json_file=args.json, csv_file=args.csv)
  File "C:\path\to\plantcv\plantcv\plantcv\utils\converters.py", line 70, in json2csv
    row.append(obs[var]["label"][i])
IndexError: list index out of range`

This is the input that I use on the command line:
`c:\path\to\plantcv\plantcv\plantcv-utils.py json2csv -j "G:\Path\To\Output\json\results.json" -c "G:\Path\To\Output\json\results"`

The script works (the CSVs are generated), so it's just the error output that needs to be addressed. I believe that I followed [the instructions](https://plantcv.readthedocs.io/en/latest/tools/#plantcv-utilities) correctly.

**Comment by nfahlgren** [comment]
Hi @AdamDimech, I am pretty sure this is an error caused by the output of `analyze_color`. Specifically there was a mismatch between the number of hue values (256) and the corresponding bin labels (180). This bug was fixed in v3.4.1 that was released a few days ago. Sorry for the trouble with this new data output format, I'm hoping it's going to be a big improvement for the long-run but we have had to work out some kinks along the way. Really appreciate you and others reporting these issues so we can get things smoothed out!

**Comment by AdamDimech** [comment]
Hi @nfahlgren.

I ran `git describe --tags` and it returned `v3.4.1-10-g6922b4b` indicating that I have the latest version, although the JSON output error remains for me. (I should note that `pip freeze` shows that I have PlantCV 3.4.0 which is clearly incorrect).

Happy to help out.... PlantCV is a great tool.

**Comment by nfahlgren** [comment]
Hi @AdamDimech, I am thinking the older version is hanging out somewhere unexpected or side-by-side with the new version somehow. Could you run this in your conda environment (either command-line python prompt or in Jupyter)?

```bash
from plantcv import plantcv as pcv
print(pcv.__version__)
print(pcv.__file__)
```

The first print will tell us if the importer is grabbing 3.4.0 or 3.4.1. The second print will tell us the file path to where the importer is grabbing the package.

**Comment by AdamDimech** [comment]
Hi @nfahlgren 

Output is as follows: 
`3.4.1+10.g6922b4b
C:\Data\plantcv\plantcv\plantcv\plantcv\__init__.py`

This is the location of my PlantCV install on my local hard drive, taken from GitHub.

**Comment by nfahlgren** [comment]
Hi @AdamDimech, when you ran the version and file commands was your Python session started from inside the plantcv clone from GitHub? Only asking because Python will import plantcv from that location even if it is installed in your environment in the `c:\data\anaconda\lib\site-packages` path.

**Comment by AdamDimech** [comment]
Hi @nfahlgren  Yes, I ran a Jupyter Notebook from inside my plantcv environment which was cloned from GitHub. Correct.

**Comment by nfahlgren** [comment]
If you start Jupyter Notebook from another location does `pcv.__version__` return 3.3.0 like `pip` does?

**Comment by AdamDimech** [comment]
Yes, I ran this from the folder where I am generating my PlantCV workflow scripts (rather than the folder containing PlantCV) and got the following output:
`3.4.0
c:\Data\Anaconda\envs\plantcv\lib\site-packages\plantcv\plantcv\__init__.py
`

**Comment by nfahlgren** [comment]
There could be something else going on but these steps should update it (below assumes your environment name is `plantcv`):

```bash
cd C:\Data\plantcv
conda activate plantcv
python setup.py install
cd C:\
pip show plantcv
```

I would expect that to output `Version: 3.4.1+10.g6922b4b`

**Comment by HaleySchuhl** [comment]
Feel free to reopen with any further suggestions/questions!
